// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izfezmfambvgoitahpfr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6ZmV6bWZhbWJ2Z29pdGFocGZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczODQzMDcsImV4cCI6MjA2Mjk2MDMwN30.Kzk21P8MMl1edLY9OBHwg5dt9_7CeGNo5BSMIualStM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);